### ISSUE TITLE
weird error message

### ISSUE THREAD

**Issue by PatNichols** [NCAR/HPCinstall#85]
pnichols/csgteam@cheyenne3:/glade/p/work/csgteam/ch_installs/gdal_install> hpcinstall -f ./build-gdal-2.1.3
Traceback (most recent call last):
  File "/glade/u/apps/ch/opt/hpcinstall/1.2.2/hpcinstall", line 529, in <module>
    options = parse_command_line_arguments(files_to_archive)
  File "/glade/u/apps/ch/opt/hpcinstall/1.2.2/hpcinstall", line 228, in parse_command_line_arguments
    num_failures += test_modules(args.modules_to_load, args.debug)
  File "/glade/u/apps/ch/opt/hpcinstall/1.2.2/hpcinstall", line 136, in test_modules
    print >> sys.stderr, term.bold_red("Modules from " + args.install_script.name + " are not loadable:")
NameError: global name 'args' is not defined

The problem is that I asked it to load ncarbinlibs....

**Comment by davidedelvento** [comment]
Ok, so that's a bug in HPCInstall, but the bug is in a piece of code that
was supposed to tell you that the modules you specified are not loadable.
Perhaps you mispelled something, or asked to load them in the wrong order.
I'll fix the bug but meanwhile you can go in your script and try to
manually load those modules exactly how they appear to see where the
problem might be.

**Comment by PatNichols** [comment]
I suppose my message was vague. I did realize that the ncar binlibs could
not be loaded on Cheyenne. You got the main meaning of my issue though. It
should actually put an error no crash.

**Comment by davidedelvento** [comment]
Yes, I got the part that I should fix, even though I did not get that you
realized what the problem was with your script.
Thanks.

**Comment by davidedelvento** [comment]
Solved by PR #86 thanks @vanderwb
