### ISSUE TITLE
Unexpected installation halt on Cheyenne

### ISSUE THREAD

**Issue by andersy005** [NCAR/HPCinstall#90]
@davidedelvento, I am trying to create an Anaconda module on Cheyenne. However, I am running into an unexpected installation halt. Below is a screenshot of the error. 

![spectacle u14716](https://user-images.githubusercontent.com/13301940/33106900-34b83710-cefa-11e7-8bbc-bc3b515b9afa.png)

When I check for the so called "unexisting file/directory", it is there. The installation script can be found at ```/glade2/scratch2/abanihi/cy/test_installs/conda/anaconda-deploy-cheyenne```

**Comment by davidedelvento** [comment]
Anderson,

The issue here is that the file `libtcl.so` exists, but it is a symbolic link to the file `libtcl8.6.so` which doesn't (broken link). 

HPCInstall does not try to discriminate actual files from symbolic link, it just compute a hash for everything, and hence the error. Now, other than giving this message (and interrupting the final step of computing and storing the hash), the install is successful, which I don't like.

So if I were to fix this, I can have two approaches: 
* ignore broken links (which might be what you want here?)
* totally fail the installation in a more "clean" way, instead of interrupting it with a stacktrace (which would be my choice: I don't like to have broken links installed).

However because of other priorities I have now, I probably won't do either, but PR are welcome

**Comment by andersy005** [comment]
@davidedelvento, Thank you for suggested approaches to solving this issue.

What I was trying to do is a bit of a hack due to my limited familiarity of using HPCinstall for interactive installations. I installed anaconda locally and I was trying to copy the install directory during the module creation. Instead, I am going to go ahead and do a clean install using the workarounds for interactive programs suggested in the documentation.

**Comment by davidedelvento** [comment]
I assume this is solved. If not reply and reopen (or ask me to reopen).
