### ISSUE TITLE
Request: Remove or bypass -c prompt

### ISSUE THREAD

**Issue by vanderwb** [NCAR/HPCinstall#91]
I'd like to run a bunch of HPCI scripts in the background... maybe even put them into a script. I can't do that because of the unavoidable stdin prompts.

I can understand the prompt about overwriting an old install. That's probably a good safety feature. But I should have some way of bypassing the "yes/no" check for non-overwrite csgteam installs, or we should just get rid of that prompt altogether. It blocks a valid use for very little gain, in my opinion.

**Comment by davidedelvento** [comment]
Just FYI, that was a design choice because HPCI was supposed to be "that last thing" that you would run, wrapping all the other things inside. Also, I wanted to make sure a production install was not done by mistake. After using it for a long while, and seeing how you use it, I understand your request.

Would be sufficient to add a `--bypass-prompt` option to make the `-c` install identical (prompt-wise) to an install without `-c`? Or do you need more?

**Comment by vanderwb** [comment]
That would be great.

**Comment by davidedelvento** [comment]
Just to make sure we are on the same page: that option is bypassing the yes/no message for installation without clobbering, but the prompt will remain for:

* clobbering installs
* attempted -c install without being csgteam user
* failed installations (it asks if you'd like to archive the logs)

Are you ok with this?

**Comment by vanderwb** [comment]
Yes, I think that's good.

**Comment by davidedelvento** [comment]
Done, released as hpcinstall v1.2.6 and installed on Cheyenne and Laramie.

Note that the following two versions were not installed on Cheyenne, so additional things now become available:

v1.2.4          Fixes for issues #84, #87, #88 and loosen the dependency on git to install
v1.2.5          Additional fixes to the install script for HPCInstall itself

(the latter was not available on Laramie either).
